export const items = [
  {
    id: 1,
    name: "1-mavzu",
    url: "https://youtu.be/jIMnB1hzmF4",
    content: "content - 1",
    panel: "panel1",
  },
  {
    id: 2,
    name: "2-mavzu",
    url: "https://youtu.be/UL-DlNiS_lg",
    content: "content - 2",
    panel: "panel2",
  },
  {
    id: 3,
    name: "3-mavzu",
    url: "https://youtu.be/npBkP1_NB3o",
    content: "content - 3",
    panel: "panel3",
  },
  {
    id: 4,
    name: "4-mavzu",
    url: "https://youtu.be/cDNU7XQQZvA",
    content: "content - 4",
    panel: "panel4",
  },
  {
    id: 5,
    name: "5-mavzu",
    url: "https://youtu.be/PT4rR0f1V3g",
    content: "content - 5",
    panel: "panel5",
  },
  {
    id: 6,
    name: "6-mavzu",
    url: "https://youtu.be/_tFXhCYBYro",
    content: "content - 6",
    panel: "panel6",
  },
  {
    id: 7,
    name: "7-mavzu",
    url: "https://youtu.be/NYQ84pCESAY",
    content: "content - 7",
    panel: "panel7",
  },
  {
    id: 8,
    name: "8-mavzu",
    url: "https://youtu.be/MIZQ28lO3gQ",
    content: "content - 8",
    panel: "panel8",
  },
  {
    id: 9,
    name: "9-mavzu",
    url: "https://youtu.be/IiaQ2JubVLQ",
    content: "content - 9",
    panel: "panel9",
  },
  {
    id: 10,
    name: "10-mavzu",
    url: "https://youtu.be/3qO5FrihZnU",
    content: "content - 10",
    panel: "panel10",
  },
];
